#version 460

#extension GL_EXT_buffer_reference : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_samplerless_texture_functions : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform texture2D kTextures2D[];

layout(std430, buffer_reference) buffer ShadowSdsmMinMaxResultBuffer {
  vec2 rawDeviceMinMax;
  uint sourceFrameIndex;
  uint valid;
};

layout(push_constant) uniform constants {
  ShadowSdsmMinMaxResultBuffer resultBuffer;
  uint sourceTexId;
  uint sourceFrameIndex;
}
pc;

void main() {
  vec4 sourceSample =
      texelFetch(kTextures2D[nonuniformEXT(pc.sourceTexId)], ivec2(0, 0), 0);
  pc.resultBuffer.rawDeviceMinMax = sourceSample.xy;
  pc.resultBuffer.sourceFrameIndex = pc.sourceFrameIndex;
  pc.resultBuffer.valid = 1u;
}
